title: Dylan Brodeur
email: dylan@onchainclarity.co
description: Dylan Brodeur's website
url: "https://dylanbrodeur.xyz"
twitter: limes_eth

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed